name: .NET

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true
    - name: BuildWindows
      run: dotnet publish -c Release -r windows-x64 -p:PublishSingleFile=True
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          /home/runner/work/DSSU/DSSU/DSSU/bin/Release/net6.0/linux-x64/publish/DSSU
          home/runner/work/DSSU/DSSU/DSSU/bin/Release/net6.0/windows-x64/publish/DSSU.exe
      

